### ISSUE TITLE
Popup is blank on Linux Firefox until right-click

### ISSUE THREAD

**Issue by daver1691** [dbaron/char-identifier#1]
With Linux Firefox, the char-identifier popup is blank until a mouse right-click (for a context menu) on the popup makes the table of characters appear.

This fault has been found with char-identifier  0.2.1 and 0.2.2
on Ubuntu 18.04 64bit (on a PC using Intel's HD graphics that's built into the CPU)
with desktops Gnome X, Gnome Wayland, and KDE.
with Firefox 60esr and 62.

(This problem is not present on Firefox 52esr, with new and old versions of char-identifier working fine.)

**Comment by dbaron** [comment]
This is bug https://bugzilla.mozilla.org/show_bug.cgi?id=1408446 which is a Firefox bug, and was fixed when out-of-process Web Extensions were enabled.

**Comment by dbaron** [comment]
... which means that it's fixed on Linux in Firefox 63.
